name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Retrieving-Bg-Info:
    uses: ./.github/workflows/reusable-workflow-info.yml
    with:
      caller-name: Super-APP!
