name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Retrieving-Bg-Info:
    uses: ./.github/workflows/reusable-workflow-info.yml
    with:
      caller-name: Super-APP!
  Building-Installing-NodeJS:
    uses: ./.github/workflows/reusable-workflow-nodejs-install-build-test.yml
    with:
      node-version: "20.x"
  Logging-Into-My-DockerHub:
    uses: ./.github/workflows/reusable-docker-login.yml
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  Scanning-Security:
    uses: ./.github/workflows/reusable-scanner-security.yml
    with:
      image-name: cesarecontini/tiny-small-node-app-test:latest
