name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Retrieving-Bg-Info:
    uses: ./.github/workflows/reusable-workflow-info.yml
    with:
      caller-name: Super-APP!
  Building-Installing-NodeJS:
    uses: ./.github/workflows/reusable-workflow-nodejs-install-build-test.yml
    with:
      node-version: '20.x'
  Logging-Into-My-DockerHub:
    uses: ./.github/workflows/reusable-docker-login.yml
    secrets: 
      inherit: true
