name: Reusable Node JS Installer, Builder, Tester
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_call: 
    inputs:
      node-version:
        type: string
        required: false
        default: '20.x'
jobs:
  NodeJs-Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
