name: ci
on:
  workflow_call:
    secrets:
      username:
        required: true
      password:
        required: true  
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
