name: Reusable Security Scan
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-name }}
          exit-code: 0
          format: table 
          
