name: Reusable Security Scan
on:
  workflow_call:
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.run_id }}
          exit-code: 0
          format: table 
          
