name: ci
on:
  workflow_call:
    inputs:
      caller-name:
        type: string
        required: false
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo " ${{ secrets.DOCKERHUB_USERNAME }} has logged in successfully into docker hub"
